# Attributes required for BigSwitch lab environment.
#

controller_user: admin
controller_password: adminadmin

mininet_user: mininet
mininet_password: mininet

switch_user: admin
switch_password: adminadmin

host_user: bsn
host_password: bsn

