# Attributes required for BigSwitch lab environment.
#

controller_user: admin
controller_password: adminadmin

switch_user: admin
switch_password: adminadmin

mininet_user: mininet
mininet_password: mininet

host_user: bsn
host_password: bsn

host_root_user: root
host_root_password: bsn
