# $ mongo qa-mongodb:27017/test_catalog_201412
#
db_server: qa-mongodb.qa.bigswitch.com
db_port: 27017
database: test_catalog_201412

products:
  - BigChain
  - BigTap
  - BigWire
  - SwitchLight
  - T5

test_types:
  - feature
  - scaling
  - performance
  - solution
  - longevity
  - negative
  - robustness

# Dictionary of products and the releases for each product as an ordered list.
product_release_map:
  bcf:
    - ironhorse        # 2.0.0
    - ironhorse-plus   # 2.1.0
    #- jackfrost        # 3.0.0
  bigtap:
    - augusta          # 2.0.0
    - blackbird        # 3.0.0
    - corsair          # 4.0.0
  
# Every release should define a set of features which we can get additional
# details for.
features:

  # Big Tap Releases
  blackbird:
    [
    ]
  corsair:
    [
    ]

  # Big Cloud Fabric Releases
  ironhorse:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite, gui, 
    ]
  ironhorse-plus:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite, gui,
    ]
  jackfrost:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite, gui, 
    ]
