# $ mongo qa-mongodb:27017/test_catalog_201412
#
db_server: qa-mongodb.qa.bigswitch.com
#db_server: localhost
db_port: 27017
database: test_catalog_201412

test_types:
  - feature
  - scaling
  - performance
  - solution
  - longevity
  - negative
  - robustness

testbeds:
  bcf:
    - virtual
    - common
    - 10g
    - 40g
  bigtap:
    - common
    - dell
    - accton
    - quantas

# Note: Releases field is an ordered list to reflect precedence, e.g.,
#       ironhorse comes before ironhorse-plus which comes before jackfrost.
products:
  bcf:
    releases:
      - ironhorse:
          version:
                   - 2.0.0
                   - 2.0.2         # patch1
          software_image_map:
                   - ih
      - ironhorse-plus:
          version:
                   - 2.5.0
          software_image_map:
                   - ihp
                   - ihplus
      - ironhorse-260:
          version:
                   - 2.6.0
          software_image_map:
                   - ih-260
                   - ih260
      - jackfrost:
          version:
                   - 3.0.0
          software_image_map:
                   - jf
      - master:
          version:
                   - top-of-tree

  bigtap:
    releases:
      - augusta:
          version:
                   - 2.0.0
          software_image_map:
                   - augusta
      - blackbird-300:
          version:
                   - 3.0.0
                   - 3.0.1
          software_image_map:
                   - blackbird300
      - blackbird-310:
          version:
                   - 3.1.0
                   - 3.1.1
          software_image_map:
                   - blackbird310
      - corsair-400:
          version:
                   - 4.0.0
                   - 4.0.1         # shellshock patch
                   - 4.0.2         # poodle patch
                   - 4.1.0         # various bug fixes
          software_image_map:
                   - corsair400
      - corsair-411:
          version:
                   - 4.1.1         # new platforms, buffer mgt
          software_image_map:
                   - corsair411
      - corsair-450:
          version:
                   - 4.5.0
          software_image_map:
                   - corsair450
      - dragon:
          version:
                   - 5.0.0
          software_image_map:
                   - dragon
      - master:
          version:
                   - top-of-tree

# Dictionary of products and the releases for each product as an ordered list.
product_release_map:
  bcf:
    - ironhorse        # 2.0.0
    - ironhorse-plus   # 2.1.0
    - jackfrost        # 3.0.0
    - master           # top-of-tree
  bigtap:
    - augusta          # 2.0.0
    - blackbird        # 3.0.0
    - corsair          # 4.0.0
    - master           # top-of-tree

# Every release should define a set of interesting features.
features:

  # Big Tap Releases
  blackbird-300:
    [ ha, user, tacacs, address_group, inport-mask, rewrite-vlan, interface, overlap, 
      match-conditions,  iptos, policy, priority, naming-convention, portchannel, 
      optimization, snmp, rbac, statistics, show-cli, vft, traffic, 
      fan, cpu, temperature, interface-rewrite, policy-rewrite, process-restart, 
      controller, l3-l4-mode, snmp-controller, reboot, switch, full-match
    ]
  blackbird-310:
    [ ha, user, tacacs, address_group, inport-mask, rewrite-vlan, interface, overlap, 
      match-conditions,  iptos, policy, priority, naming-convention, portchannel, 
      optimization, snmp, rbac, statistics, show-cli, vft, traffic, 
      fan, cpu, temperature, interface-rewrite, policy-rewrite, process-restart, 
      controller, l3-l4-mode, snmp-controller, reboot, switch, full-match
    ]    
  corsair-400:
    [ environment, snmp-controller, ha, user, tacacs, address_group, inport-mask, 
      rewrite-vlan, interface, overlap, tunnel, trident2, trident-plus, back-pressure, 
      buffer, breakout, tcp-flags, sflow, timed-policy, interface-group, dpm, 
      match-conditions,  iptos, policy, priority, naming-convention, portchannel,
      optimization, snmp, rbac, statistics, show-cli, vft, traffic, 
      fan, cpu, temperature, interface-rewrite, policy-rewrite, process-restart, 
      controller, l3-l4-mode, snmp-controller, reboot, switch, full-match
    ]
  corsair-411:
    [ environment, snmp-controller, ha, user, tacacs, address_group, inport-mask, 
      rewrite-vlan, interface, overlap, tunnel, trident2, trident-plus, back-pressure, 
      buffer, breakout, tcp-flags, sflow, timed-policy, interface-group, dpm, 
      match-conditions,  iptos, policy, priority, naming-convention, portchannel,
      optimization, snmp, rbac, statistics, show-cli, vft, traffic, 
      fan, cpu, temperature, interface-rewrite, policy-rewrite, process-restart, 
      controller, l3-l4-mode, snmp-controller, reboot, switch, full-match
    ]
  corsair-450:
    [ environment, snmp-controller, ha, user, tacacs, address_group, inport-mask, 
      rewrite-vlan, interface, overlap, tunnel, trident2, trident-plus, back-pressure, 
      buffer, breakout, tcp-flags, sflow, timed-policy, interface-group, dpm, 
      match-conditions,  iptos, policy, priority, naming-convention, portchannel,
      optimization, snmp, rbac, statistics, show-cli, vft, traffic, 
      fan, cpu, temperature, interface-rewrite, policy-rewrite, process-restart, 
      controller, l3-l4-mode, snmp-controller, reboot, switch, full-match
    ]

  # Big Cloud Fabric Releases
  ironhorse:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite, gui, 
    ]
  ironhorse-plus:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite, gui,
    ]
  jackfrost:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite, gui, 
    ]

