# $ mongo qa-mongodb:27017/test_catalog3
#
db_server: qa-mongodb.qa.bigswitch.com
db_port: 27017
#database: test_catalog3
database: test_catalog3_20140806
products:
  - BigChain
  - BigTap
  - BigWire
  - SwitchLight
  - T5
test_types:
  - feature
  - scaling
  - performance
  - solution
  - longevity
  - negative
  - robustness
features:
  ironhorse:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite
    ]

# For "milestone" builds under qualification (e.g., B1, B2, R1, etc), there may
# be multiple builds which need to be aggregated. The data structure below
# specifies which builds are part of an aggregated build.
aggregated_builds:
  'bvs master ironhorse beta2 aggregated':    # 2014-08 IronHorse Beta 2
    [ 
      #'bvs master #beta2_14',
      'bvs master #beta2_15',
    ] 
  'bvs master aggregated 2014 wk32':          # week of 2014-08-04
    [ 
      'bvs master #2806',
      'bvs master #2821',
      'bvs master #2837',
    ]
  'bvs master aggregated 2014 wk31':          # week of 2014-07-28
    [ 
      'bvs master #2685',
      'bvs master #2710',
    ]
  'bvs master #beta1-vui':
    [ 
      'bvs master #2.0.0-beta1-SNAPSHOT',
      'bvs master #beta1-22',
      'bvs master #beta1-27',
      'bvs master #beta1-31',
    ]
  'bvs master ironhorse beta1 aggregated':    # 2014-06 IronHorse Beta 1
    [ 
      'bvs master #2.0.0-beta1-SNAPSHOT',
      'bvs master #beta1-22',
      'bvs master #beta1-27',
      'bvs master #beta1-31',
      'bvs master #2502',
    ]
