db_server: qa-mongodb.qa.bigswitch.com
db_port: 27017
database: test_catalog3
products:
  - BigChain
#  - BigTap
#  - BigWire
#  - SwitchLight
#  - T5
test_types:
  - feature
  - scaling
  - performance
  - solution
  - longevity
  - negative
  - robustness
features:
  ironhorse:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite
    ]

# For "milestone" builds under qualification (e.g., B1, B2, R1, etc), there may
# be multiple builds which need to be aggregated. The data structure below
# specifies which builds are part of an aggregated build.
aggregated_builds:
  'bvs master #beta1-vui':
    [ 
      'bvs master #2.0.0-beta1-SNAPSHOT',
      'bvs master #beta1-22',
      'bvs master #beta1-27',
      'bvs master #beta1-31',
    ]
  'bvs master ironhorse beta1 aggregated':    # 2014-06 IronHorse Beta1
    [ 
      'bvs master #2.0.0-beta1-SNAPSHOT',
      'bvs master #beta1-22',
      'bvs master #beta1-27',
      'bvs master #beta1-31',
    ]

