# $ mongo qa-mongodb:27017/test_catalog_201412
#
db_server: qa-mongodb.qa.bigswitch.com
db_port: 27017
database: test_catalog_201412

test_types:
  - feature
  - scaling
  - performance
  - solution
  - longevity
  - negative
  - robustness

# Note: releases field is an ordered list to reflect precedence, e.g.,
#       ironhorse comes before ironhorse-plus which comes before jackfrost.
products:
  bcf:
    releases:
      - ironhorse:
          version:
                   - 2.0.0
                   - 2.0.2         # patch1
          software_image_map:
                   - ih
                   - ironhorse
      - ironhorse-plus:
          version:
                   - 2.5.0
          software_image_map:
                   - ihp
                   - ihplus
                   - ironhorse-plus
      - jackfrost:
          version:
                   - 3.0.0
          software_image_map:
                   - jf
                   - jackfrost

  bigtap:
    releases:
      - augusta:
          version:
                   - 2.0.0
          software_image_map:
                   - augusta
      - blackbird:
          version:
                   - 3.0.0
          software_image_map:
                   - blackbird
      - corsair-400:
          version:
                   - 4.0.0
                   - 4.0.1         # shellshock patch
                   - 4.0.2         # poodle patch
                   - 4.1.0         # various bug fixes
          software_image_map:
                   - corsair400
      - corsair-411:
          version:
                   - 4.1.1         # new platforms, buffer mgt
          software_image_map:
                   - corsair411
      - corsair-450:
          version:
                   - 4.5.0
          software_image_map:
                   - corsair450
      - dragon:
          version:
                   - 5.0.0
          software_image_map:
                   - dragon

# Dictionary of products and the releases for each product as an ordered list.
product_release_map:
  bcf:
    - ironhorse        # 2.0.0
    - ironhorse-plus   # 2.1.0
    - jackfrost        # 3.0.0
  bigtap:
    - augusta          # 2.0.0
    - blackbird        # 3.0.0
    - corsair          # 4.0.0

# Every release should define a set of interesting features.
features:

  # Big Tap Releases
  blackbird:
    [
    ]
  corsair:
    [
    ]

  # Big Cloud Fabric Releases
  ironhorse:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite, gui, 
    ]
  ironhorse-plus:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite, gui,
    ]
  jackfrost:
    [ ha, span, testpath, pod, l2, l3, snmp, ntp, traffic, logging, rsyslog,
      rsyslogd, install, initialconfig, rebootswitch, firstboot, upgrade,
      singlenode, bpdu_guard, fabric, fabric_qos, qos, ztn, file management,
      filemanagement, running-config, initialconfig, virtualip, openstack,
      dhcp, dhcp-relay, ecmp, policy, policy-vlanrewrite, gui, 
    ]

